# Generated by Django 3.2.13 on 2022-06-02 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_eventdetailpage_submit_form_link'),
        ('users', '0004_favoriteevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteScholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.scholarshipdetailpage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FavoriteEvent',
                'verbose_name_plural': 'FavoriteEvents',
                'ordering': ['id'],
            },
        ),
    ]
