# Generated by Django 3.2.13 on 2022-06-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_eventdetailpage_submit_form_link'),
        ('users', '0005_favoritescholarship'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteEvent',
            new_name='FavouriteEvent',
        ),
        migrations.RenameModel(
            old_name='FavoriteScholarship',
            new_name='FavouriteScholarship',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
