# Generated by Django 3.2.13 on 2022-06-02 17:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220602_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=uuid.uuid1, max_length=24, unique=True, verbose_name='Phone Number'),
        ),
    ]
