# Generated by Django 3.2.13 on 2022-06-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220603_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=24, unique=True, verbose_name='Phone Number'),
        ),
    ]
