# Generated by Django 3.2.13 on 2022-06-16 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20220611_0900'),
        ('users', '0014_bloglikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglikes',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='like_blog', to='blog.blogdetailpage'),
        ),
        migrations.AlterField(
            model_name='bloglikes',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='like_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
