# Generated by Django 3.2.13 on 2022-06-16 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_bloglikestest'),
        ('users', '0015_auto_20220616_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglikes',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.blogdetailpage'),
        ),
    ]
