# Generated by Django 3.2.13 on 2022-06-23 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_delete_bloglikes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentevent',
            old_name='content',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='commentevent',
            name='user',
        ),
    ]
