# Generated by Django 3.2.11 on 2022-01-23 10:39

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogcategories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogCategories',
            new_name='BlogCategory',
        ),
        migrations.AddField(
            model_name='blogdetailpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='blog.BlogCategory'),
        ),
    ]
