# Generated by Django 3.2.13 on 2022-06-11 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_scholarshipdetailpage_favourites'),
        ('blog', '0008_videoblogpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogauthorsorderable',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.author'),
        ),
        migrations.DeleteModel(
            name='BlogAuthor',
        ),
    ]
