# Generated by Django 3.2.13 on 2022-06-16 09:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0011_bloglikestest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogLikesTest',
            new_name='BlogLikes',
        ),
    ]
