# Generated by Django 3.2.11 on 2022-02-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='sequence',
            field=models.IntegerField(default=1),
        ),
    ]
