# Generated by Django 3.2.11 on 2022-02-06 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetailpage',
            name='published_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Published Datetime'),
        ),
        migrations.AddField(
            model_name='scholarshipdetailpage',
            name='published_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Published Datetime'),
        ),
    ]
