# Generated by Django 3.2.11 on 2022-02-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20220206_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetailpage',
            name='submit_form_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
