# Generated by Django 3.2.13 on 2022-06-07 09:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0003_eventdetailpage_submit_form_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetailpage',
            name='favourite',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
