# Generated by Django 3.2.13 on 2022-06-07 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_eventdetailpage_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventdetailpage',
            old_name='favourite',
            new_name='favourites',
        ),
    ]
