# Generated by Django 3.2.13 on 2022-06-07 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0005_rename_favourite_eventdetailpage_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetailpage',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite_event', to=settings.AUTH_USER_MODEL),
        ),
    ]
