# Generated by Django 3.2.13 on 2022-06-07 16:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0006_alter_eventdetailpage_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipdetailpage',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite_scholarship', to=settings.AUTH_USER_MODEL),
        ),
    ]
