# Generated by Django 3.2.13 on 2022-06-16 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0007_scholarshipdetailpage_favourites'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scholarship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='like_scholarship', to='content.scholarshipdetailpage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_like_scholarship', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Like',
                'verbose_name_plural': 'Event Likes',
            },
        ),
        migrations.CreateModel(
            name='EventLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='like_event', to='content.eventdetailpage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_like_event', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Like',
                'verbose_name_plural': 'Event Likes',
            },
        ),
    ]
