# Generated by Django 3.2.13 on 2022-06-16 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_eventlikes_scholarshiplikes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventlikes',
            old_name='event',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='scholarshiplikes',
            old_name='scholarship',
            new_name='post',
        ),
    ]
