# Generated by Django 3.2.13 on 2022-06-16 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20220616_0720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scholarshiplikes',
            options={'verbose_name': 'Scholarship Like', 'verbose_name_plural': 'Scholarship Likes'},
        ),
    ]
