# Generated by Django 3.2.13 on 2022-06-22 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20220622_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscholarshiplistingpage',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.scholarshipcategory'),
        ),
    ]
