# Generated by Django 3.2.13 on 2022-06-22 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_newscholarshiplistingpage_custom_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipdetailpage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.scholarshipcategory'),
        ),
    ]
