# Generated by Django 3.2.13 on 2022-06-22 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_alter_scholarshipdetailpage_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarshipdetailpage',
            name='scholarship_category',
        ),
        migrations.AlterField(
            model_name='scholarshipdetailpage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scholarship_category', to='content.scholarshipcategory'),
        ),
    ]
